[package]
name = "your_language_name"
version = "0.1.0"
edition = "2021"

# Specify the library type
[lib]
name = "asura"
path = "src/lib.rs"

[dependencies]
logos = "0.12.0"  # For lexing
chumsky = "0.8.0" # For parsing
wasm-bindgen = "0.2.83" # For WASM integration
